<html>
<head><meta charset="utf-8"><title>✔ wasmtime-py canonical_abi_realloc failure · wasmtime · Zulip Chat Archive</title></head>
<h2>Stream: <a href="https://bytecodealliance.github.io/zulip-archive/stream/217126-wasmtime/index.html">wasmtime</a></h2>
<h3>Topic: <a href="https://bytecodealliance.github.io/zulip-archive/stream/217126-wasmtime/topic/.E2.9C.94.20wasmtime-py.20canonical_abi_realloc.20failure.html">✔ wasmtime-py canonical_abi_realloc failure</a></h3>

<hr>

<base href="https://bytecodealliance.zulipchat.com">

<head><link href="https://bytecodealliance.github.io/zulip-archive/style.css" rel="stylesheet"></head>

<a name="288919036"></a>
<h4><a href="https://bytecodealliance.zulipchat.com#narrow/stream/217126-wasmtime/topic/%E2%9C%94%20wasmtime-py%20canonical_abi_realloc%20failure/near/288919036" class="zl"><img src="https://bytecodealliance.github.io/zulip-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Jens Gåsemyr Magnus <a href="https://bytecodealliance.github.io/zulip-archive/stream/217126-wasmtime/topic/.E2.9C.94.20wasmtime-py.20canonical_abi_realloc.20failure.html#288919036">(Jul 08 2022 at 09:46)</a>:</h4>
<p>I have an issue where calling <code>canonical_abi_realloc</code> from Python after linking causes an error: <code>thread '&lt;unnamed&gt;' panicked at 'called `Option::unwrap()` on a `None` value', crates/c-api/src/linker.rs:105:80</code>, anyone know what this could be? Version conflicts? I am running this in an linux arm64 vm on an arm mac</p>



<a name="288922974"></a>
<h4><a href="https://bytecodealliance.zulipchat.com#narrow/stream/217126-wasmtime/topic/%E2%9C%94%20wasmtime-py%20canonical_abi_realloc%20failure/near/288922974" class="zl"><img src="https://bytecodealliance.github.io/zulip-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> bjorn3 <a href="https://bytecodealliance.github.io/zulip-archive/stream/217126-wasmtime/topic/.E2.9C.94.20wasmtime-py.20canonical_abi_realloc.20failure.html#288922974">(Jul 08 2022 at 10:32)</a>:</h4>
<p>That is an error in <code>wasmtime_linker_define_wasi</code> which seems to happen when the wasi context is not set. This field seems to be set by <code>wasmtime_context_set_wasi</code>. It seems you have to call <code>store.set_wasi(wasi)</code> on the python side before instantiating the linker. <code>wasi</code> here is of the type <code>WasiConfig</code>. See <a href="https://github.com/bytecodealliance/wasmtime-py/blob/7ebdf1cb0c792da8c6b4c9b54630ac0da1a6a655/examples/linking.py#L20">https://github.com/bytecodealliance/wasmtime-py/blob/7ebdf1cb0c792da8c6b4c9b54630ac0da1a6a655/examples/linking.py#L20</a></p>
<div class="message_embed"><a class="message_embed_image" href="https://github.com/bytecodealliance/wasmtime-py/blob/7ebdf1cb0c792da8c6b4c9b54630ac0da1a6a655/examples/linking.py#L20" style="background-image: url(https\:\/\/uploads\.zulipusercontent\.net\/7b317b986b55046d2debc9debdde95edc1abf322\/68747470733a2f2f6f70656e67726170682e6769746875626173736574732e636f6d2f616335323033366133303035386235666664383431623666323932646139346665343035356464363633363363346438656264343562303062653637353930302f62797465636f6465616c6c69616e63652f7761736d74696d652d7079)"></a><div class="data-container"><div class="message_embed_title"><a href="https://github.com/bytecodealliance/wasmtime-py/blob/7ebdf1cb0c792da8c6b4c9b54630ac0da1a6a655/examples/linking.py#L20" title="wasmtime-py/linking.py at 7ebdf1cb0c792da8c6b4c9b54630ac0da1a6a655 · bytecodealliance/wasmtime-py">wasmtime-py/linking.py at 7ebdf1cb0c792da8c6b4c9b54630ac0da1a6a655 · bytecodealliance/wasmtime-py</a></div><div class="message_embed_description">Python WebAssembly runtime powered by Wasmtime. Contribute to bytecodealliance/wasmtime-py development by creating an account on GitHub.</div></div></div>



<a name="288948245"></a>
<h4><a href="https://bytecodealliance.zulipchat.com#narrow/stream/217126-wasmtime/topic/%E2%9C%94%20wasmtime-py%20canonical_abi_realloc%20failure/near/288948245" class="zl"><img src="https://bytecodealliance.github.io/zulip-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Jens Gåsemyr Magnus <a href="https://bytecodealliance.github.io/zulip-archive/stream/217126-wasmtime/topic/.E2.9C.94.20wasmtime-py.20canonical_abi_realloc.20failure.html#288948245">(Jul 08 2022 at 14:34)</a>:</h4>
<p>Thanks! This was indeed the issue, works perfectly now!</p>



<a name="288963481"></a>
<h4><a href="https://bytecodealliance.zulipchat.com#narrow/stream/217126-wasmtime/topic/%E2%9C%94%20wasmtime-py%20canonical_abi_realloc%20failure/near/288963481" class="zl"><img src="https://bytecodealliance.github.io/zulip-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Notification Bot <a href="https://bytecodealliance.github.io/zulip-archive/stream/217126-wasmtime/topic/.E2.9C.94.20wasmtime-py.20canonical_abi_realloc.20failure.html#288963481">(Jul 08 2022 at 16:32)</a>:</h4>
<p><span class="user-mention silent" data-user-id="264278">bjorn3</span> has marked this topic as resolved.</p>



<hr><p>Last updated: Jan 20 2025 at 06:04 UTC</p>
</html>