<html>
<head><meta charset="utf-8"><title>assertion failed: self.stacks.is_empty() · wasmtime · Zulip Chat Archive</title></head>
<h2>Stream: <a href="https://bytecodealliance.github.io/zulip-archive/stream/217126-wasmtime/index.html">wasmtime</a></h2>
<h3>Topic: <a href="https://bytecodealliance.github.io/zulip-archive/stream/217126-wasmtime/topic/assertion.20failed.3A.20self.2Estacks.2Eis_empty.28.29.html">assertion failed: self.stacks.is_empty()</a></h3>

<hr>

<base href="https://bytecodealliance.zulipchat.com">

<head><link href="https://bytecodealliance.github.io/zulip-archive/style.css" rel="stylesheet"></head>

<a name="493430639"></a>
<h4><a href="https://bytecodealliance.zulipchat.com#narrow/stream/217126-wasmtime/topic/assertion%20failed%3A%20self.stacks.is_empty%28%29/near/493430639" class="zl"><img src="https://bytecodealliance.github.io/zulip-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Tomas Olvecky <a href="https://bytecodealliance.github.io/zulip-archive/stream/217126-wasmtime/topic/assertion.20failed.3A.20self.2Estacks.2Eis_empty.28.29.html#493430639">(Jan 13 2025 at 19:27)</a>:</h4>
<p>After updating to wasmtime 28 I see a panic with the message above when shutting down wasmtime: <a href="https://github.com/bytecodealliance/wasmtime/blob/release-28.0.0/crates/wasmtime/src/runtime/vm/instance/allocator/pooling.rs#L319">pooling.rs#L319</a><br>
Is there a cleanup I have to perform when using the pooling allocator?</p>
<div class="message_embed"><a class="message_embed_image" href="https://github.com/bytecodealliance/wasmtime/blob/release-28.0.0/crates/wasmtime/src/runtime/vm/instance/allocator/pooling.rs#L319" style="background-image: url(&quot;https://uploads.zulipusercontent.net/bdc75718a7905befa63577501295803c56017d2d/68747470733a2f2f6f70656e67726170682e6769746875626173736574732e636f6d2f623639353461646566373834396538353638393336383766623863326337303036306132653066373564663965643337613161383265646530366437333737342f62797465636f6465616c6c69616e63652f7761736d74696d65&quot;)"></a><div class="data-container"><div class="message_embed_title"><a href="https://github.com/bytecodealliance/wasmtime/blob/release-28.0.0/crates/wasmtime/src/runtime/vm/instance/allocator/pooling.rs#L319" title="wasmtime/crates/wasmtime/src/runtime/vm/instance/allocator/pooling.rs at release-28.0.0 · bytecodealliance/wasmtime">wasmtime/crates/wasmtime/src/runtime/vm/instance/allocator/pooling.rs at release-28.0.0 · bytecodealliance/wasmtime</a></div><div class="message_embed_description">A lightweight WebAssembly runtime that is fast, secure, and standards-compliant - bytecodealliance/wasmtime</div></div></div>



<a name="493431208"></a>
<h4><a href="https://bytecodealliance.zulipchat.com#narrow/stream/217126-wasmtime/topic/assertion%20failed%3A%20self.stacks.is_empty%28%29/near/493431208" class="zl"><img src="https://bytecodealliance.github.io/zulip-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Alex Crichton <a href="https://bytecodealliance.github.io/zulip-archive/stream/217126-wasmtime/topic/assertion.20failed.3A.20self.2Estacks.2Eis_empty.28.29.html#493431208">(Jan 13 2025 at 19:30)</a>:</h4>
<p>Hm that may indicate a bug because nothing about that should have changed. You're not <code>mem::forget</code>-ing anything are you?</p>



<a name="493441188"></a>
<h4><a href="https://bytecodealliance.zulipchat.com#narrow/stream/217126-wasmtime/topic/assertion%20failed%3A%20self.stacks.is_empty%28%29/near/493441188" class="zl"><img src="https://bytecodealliance.github.io/zulip-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Tomas Olvecky <a href="https://bytecodealliance.github.io/zulip-archive/stream/217126-wasmtime/topic/assertion.20failed.3A.20self.2Estacks.2Eis_empty.28.29.html#493441188">(Jan 13 2025 at 20:25)</a>:</h4>
<p>Nope. If I start the server and perform the graceful shutdown without running any executions, the panic won't appear.</p>



<a name="493444548"></a>
<h4><a href="https://bytecodealliance.zulipchat.com#narrow/stream/217126-wasmtime/topic/assertion%20failed%3A%20self.stacks.is_empty%28%29/near/493444548" class="zl"><img src="https://bytecodealliance.github.io/zulip-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Alex Crichton <a href="https://bytecodealliance.github.io/zulip-archive/stream/217126-wasmtime/topic/assertion.20failed.3A.20self.2Estacks.2Eis_empty.28.29.html#493444548">(Jan 13 2025 at 20:43)</a>:</h4>
<p>Hm ok, how easy would it be to either reduce this to something you can share or share reproduction steps?</p>



<a name="493563266"></a>
<h4><a href="https://bytecodealliance.zulipchat.com#narrow/stream/217126-wasmtime/topic/assertion%20failed%3A%20self.stacks.is_empty%28%29/near/493563266" class="zl"><img src="https://bytecodealliance.github.io/zulip-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Tomas Olvecky <a href="https://bytecodealliance.github.io/zulip-archive/stream/217126-wasmtime/topic/assertion.20failed.3A.20self.2Estacks.2Eis_empty.28.29.html#493563266">(Jan 14 2025 at 11:23)</a>:</h4>
<p>I've managed to reproduce the issue in the wasmtime repo, created an issue for it <a href="https://github.com/bytecodealliance/wasmtime/issues/10007">here</a></p>
<div class="message_embed"><a class="message_embed_image" href="https://github.com/bytecodealliance/wasmtime/issues/10007" style="background-image: url(&quot;https://uploads.zulipusercontent.net/77af8e86f3d9c52175ed3afe316c21b0d329cf04/68747470733a2f2f6f70656e67726170682e6769746875626173736574732e636f6d2f373364336334323631653665633763386639646461323361316562663239303463353037343636616563616539633665383066623538383534373739363737652f62797465636f6465616c6c69616e63652f7761736d74696d652f6973737565732f3130303037&quot;)"></a><div class="data-container"><div class="message_embed_title"><a href="https://github.com/bytecodealliance/wasmtime/issues/10007" title="Calling `store.into_data()` after an execution triggers a debug assertion failure in `drop` of the pooling allocator · Issue #10007 · bytecodealliance/wasmtime">Calling `store.into_data()` after an execution triggers a debug assertion failure in `drop` of the pooling allocator · Issue #10007 · bytecodealliance/wasmtime</a></div><div class="message_embed_description">Calling store.into_data() after an execution finishes will trigger a panic in this debug assertion of the pooling allocator's drop method. Test Case This commit will trigger the bug in a test: toma...</div></div></div>



<a name="493611220"></a>
<h4><a href="https://bytecodealliance.zulipchat.com#narrow/stream/217126-wasmtime/topic/assertion%20failed%3A%20self.stacks.is_empty%28%29/near/493611220" class="zl"><img src="https://bytecodealliance.github.io/zulip-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Alex Crichton <a href="https://bytecodealliance.github.io/zulip-archive/stream/217126-wasmtime/topic/assertion.20failed.3A.20self.2Estacks.2Eis_empty.28.29.html#493611220">(Jan 14 2025 at 15:32)</a>:</h4>
<p>thanks!</p>



<hr><p>Last updated: Jan 20 2025 at 06:04 UTC</p>
</html>