[
    {
        "content": "<p>alexcrichton <a href=\"https://github.com/bytecodealliance/wasmtime/pull/6305#issuecomment-1527803515\">commented</a> on <a href=\"https://github.com/bytecodealliance/wasmtime/pull/6305\">issue #6305</a>:</p>\n<blockquote>\n<p>My best guess as to what happened here: there's a \"well known\" bug in this fuzzer where a type can get too big and at that point it fails validation. That's been on my todo-list for a very long time. It appears that OSS-Fuzz took this different validation failure and \"dedup'd\" it with the previous one, meaning that this bug, which prevents the fuzzer from running at all, wasn't caught since we didn't get a separate notification about it.</p>\n</blockquote>",
        "id": 353965646,
        "sender_full_name": "Wasmtime GitHub notifications bot",
        "timestamp": 1682699238
    }
]