[
    {
        "content": "<p>abrown <a href=\"https://github.com/bytecodealliance/wasmtime/pull/2475#issuecomment-738558533\">commented</a> on <a href=\"https://github.com/bytecodealliance/wasmtime/pull/2475\">Issue #2475</a>:</p>\n<blockquote>\n<p>No idea what the trouble is with CI. It's failing during <a href=\"https://github.com/bytecodealliance/wasmtime/pull/2475/checks?check_run_id=1496832995#step:2:488\">submodule checkout here</a>?</p>\n</blockquote>",
        "id": 218793464,
        "sender_full_name": "Wasmtime GitHub notifications bot",
        "timestamp": 1607056399
    },
    {
        "content": "<p>cfallin <a href=\"https://github.com/bytecodealliance/wasmtime/pull/2475#issuecomment-738584596\">commented</a> on <a href=\"https://github.com/bytecodealliance/wasmtime/pull/2475\">Issue #2475</a>:</p>\n<blockquote>\n<p>I was seeing that earlier too; after a few restarts the jobs went through. I had assumed it was some sort of spurious-failed-HTTP-request error. I'll hit the 're-run jobs' button for these...</p>\n</blockquote>",
        "id": 218797089,
        "sender_full_name": "Wasmtime GitHub notifications bot",
        "timestamp": 1607061667
    }
]