[
    {
        "content": "<p>Apparently I don't have merge permissions for <code>wasmtime-py</code>, but this PR LGTM: <a href=\"https://github.com/bytecodealliance/wasmtime-py/pull/45\">https://github.com/bytecodealliance/wasmtime-py/pull/45</a></p>\n<div class=\"message_embed\"><a class=\"message_embed_image\" href=\"https://github.com/bytecodealliance/wasmtime-py/pull/45\" style=\"background-image: url(https://avatars0.githubusercontent.com/u/54038801?s=400&amp;v=4)\"></a><div class=\"data-container\"><div class=\"message_embed_title\"><a href=\"https://github.com/bytecodealliance/wasmtime-py/pull/45\" title=\"Fixed Python hello example on README.md by viniarck 路 Pull Request #45 路 bytecodealliance/wasmtime-py\">Fixed Python hello example on README.md by viniarck 路 Pull Request #45 路 bytecodealliance/wasmtime-py</a></div><div class=\"message_embed_description\">When I first tried out the example in the README.md, I hit this TypeError exception:\nTraceback (most recent call last):\n  File &quot;ex.py&quot;, line 4, in &lt;module&gt;\n    module = Module(store...</div></div></div>",
        "id": 210775463,
        "sender_full_name": "fitzgen (he/him)",
        "timestamp": 1600710256
    },
    {
        "content": "<p>so it would be nice if someone who did have perms merged it</p>",
        "id": 210775500,
        "sender_full_name": "fitzgen (he/him)",
        "timestamp": 1600710281
    },
    {
        "content": "<p>I see Alex merged the PR, but I now also gave wasmtime-core write permissions to the repo. One of these days we'll clean all of this up ...</p>",
        "id": 210903596,
        "sender_full_name": "Till Schneidereit",
        "timestamp": 1600795438
    }
]